project:
  type: website

execute:
  freeze: auto

website:
  site-url: https://lifeint.online
  repo-url: https://github.com/lifeint/lifeint-web
  navbar:
    logo: img/LIFE_logo_white_recreated.png
    logo-alt: "LIFE logo."
    title: false
    collapse-below: lg
    left:
      - href: index.qmd
        text: "Home"
      - text: "The Chosen"
        href: thechosen/index.qmd
      - about.qmd
  sidebar: 
    - title: "The Chosen"
      style: "docked"
      contents: 
        - thechosen/index.qmd
        - section: "Season 1"
          href: thechosen/season1.qmd
          contents: thechosen/season1/* 
        - section: "Season 2"
          href: thechosen/season2.qmd
          contents: thechosen/season2/* 

format:
  html:
    theme:
      - sandstone
    toc: true



